<footer class="hidden-print">
  <div class="footer-container">
		<div class="logo-pie">
			<a href="http://ruie.ucr.ac.cr"><img src="/catalogo/themes/inie/images/logo-footer.svg"></a>
		</div>
		    
		<div class ="footer-links">
		  <div class="footer-column">   
			<p><strong>Noticias y eventos</strong></p>
				<ul>
					<li><a href="#">Novedades</a></li>
					<li><a href="#">Eventos</a></li>
				</ul>
			</div>
		  <div class="footer-column">
			<p><strong>Servicios</strong></p>
			<ul>
				<li><a href="http://ruie.ucr.ac.cr/centros-participantes">Centros de Documentación</a></li>
				<li><a href="http://ruie.ucr.ac.cr/servicios">Servicios</a></li>
				<li><a href="http://ruie.ucr.ac.cr/contacto">Contáctenos</a></li>
			</ul>
		  </div>
		  <div class="footer-column">
			<p><strong>Sobre nosotros</strong></p>
			<ul>
				<li><a href="http://ruie.ucr.ac.cr/quienes-somos/historia">Historia</a></li>
			</ul>
		</div>
		</div>
		<div class="creditos">
			<a href="http://ucr.ac.cr">©2018 Universidad de Costa Rica</a>
			<a href="http://inie.ucr.ac.cr">Instituto de Investigación en Educación</a>
			<a href="#">Créditos</a>
		</div>
	</div>
</footer>
